<?php

define('TABLE_PURCHASE_LIST', 'purchase_list');
define('TABLE_PURCHASE_LIST_EVENTS', 'purchase_list_events');

define('PURCHASE_LIST_EVENT_ADD', 'add');
define('PURCHASE_LIST_EVENT_IMPORT', 'import');
define('PURCHASE_LIST_EVENT_UPDATE', 'update');
define('PURCHASE_LIST_EVENT_SHOPPING', 'shopping');
define('PURCHASE_LIST_EVENT_DELETE', 'delete');
define('PURCHASE_LIST_EVENT_DELETE_ALL', 'delete_all');

define('ERROR_EXISTING_ITEM', 'APP_ERROR_EXISTING_ITEM_WITH_SAME_NAME');
define('ERROR_NON_EDITABLE_ITEM', 'APP_ERROR_NON_EDITABLE_ITEM');
define('ERROR_NOT_JSON_FILE', 'APP_ERROR_NOT_JSON_FILE');
define('ERROR_ITEMS_ALREADY_IN_SHOPPING', 'APP_ERROR_ITEMS_ALREADY_IN_SHOPPING');
define('ERROR_ITEM_NOT_IN_SHOPPING', 'APP_ERROR_ITEM_NOT_IN_SHOPPING');
define('ERROR_NO_ITEMS_AVAILABLE_FOR_SHOPPING', 'APP_ERROR_NO_ITEMS_AVAILABLE_FOR_SHOPPING');
define('ERROR_USER_NOT_SHOPPING_OWNER', 'APP_ERROR_USER_NOT_SHOPPING_OWNER');
define('ERROR_CHECKED_QUANITY_LARGER_THAN_QUANTITY', 'APP_ERROR_CHECKED_QUANITY_LARGER_THAN_QUANTITY');